# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(null=True, to='app.Course'),
        ),
    ]
