# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20151228_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(null=True, to='app.Student'),
        ),
    ]
